### ISSUE TITLE
Segregate Final Design Screens on Figma

### ISSUE THREAD

**Issue by msclal** [msclal/below-zero#14]
figuring out which version of screens to look at is a guessing game

<img width="1086" alt="Screenshot 2024-03-16 at 2 27 10 AM" src="https://github.com/msclal/below-zero/assets/60799725/e99ea383-df6e-4d21-bcf7-b7ac02cc2f7f">

**Comment by bobbyyy57** [comment]
Final Designs are on another page: 

![image](https://github.com/msclal/below-zero/assets/72523111/9e02d6e3-97ba-4120-89ad-fee9ee31f22a)
![image](https://github.com/msclal/below-zero/assets/72523111/37a7622b-da07-4ca5-a3d4-f59c5f89202f)
