### ISSUE TITLE
Inconsistent Color Upon Item Change on Landing

### ISSUE THREAD

**Issue by bobbyyy57** [msclal/below-zero#34]
https://github.com/msclal/below-zero/assets/72523111/f9b4d598-4139-4780-a16c-865fb331f944

color of arrow should match the button bg

**Comment by msclal** [comment]
giving you this per verbal agreement

<img width="707" alt="image" src="https://github.com/msclal/below-zero/assets/60799725/12468c8d-743b-4838-9b03-f7bb0f66765c">
